import Foundation
import IdentifiedCollections

/// The editor's undoable document: everything a saved project package persists
/// (slices, timeline removals, cut suggestions, speaker overrides) moves together, so
/// undo/redo restores all of it in one step. Deliberately excludes everything else the
/// editor tracks (selection, zoom, playback, export phase) — only the document itself.
struct EditorDocumentState: Equatable, Codable, Sendable {
  var slices: IdentifiedArrayOf<Slice>
  var timelineRemovals: IdentifiedArrayOf<TimelineRemoval>
  var cutSuggestions: IdentifiedArrayOf<CutSuggestion>
  var suggestionStarts: SuggestionStarts
  var suggestionBatch: SuggestionBatch?
  var issuedSuggestionNumbers: [SequenceReservation]
  var unfinishedSuggestionRun: SuggestionRunCheckpoint?
  var lastAppliedSuggestionRunID: UUID?
  var suggestionRecoveryOwnerID: UUID?
  var speakerCountOverride: Int?
  var speakerDisplayNames: [String: String]

  init(
    slices: IdentifiedArrayOf<Slice> = [],
    timelineRemovals: IdentifiedArrayOf<TimelineRemoval> = [],
    cutSuggestions: IdentifiedArrayOf<CutSuggestion> = [],
    suggestionStarts: SuggestionStarts = SuggestionStarts(),
    suggestionBatch: SuggestionBatch? = nil,
    issuedSuggestionNumbers: [SequenceReservation] = [],
    unfinishedSuggestionRun: SuggestionRunCheckpoint? = nil,
    lastAppliedSuggestionRunID: UUID? = nil,
    suggestionRecoveryOwnerID: UUID? = nil,
    speakerCountOverride: Int? = nil,
    speakerDisplayNames: [String: String] = [:]
  ) {
    self.slices = slices
    self.timelineRemovals = timelineRemovals
    self.cutSuggestions = cutSuggestions
    self.suggestionStarts = suggestionStarts
    self.suggestionBatch = suggestionBatch
    self.issuedSuggestionNumbers = issuedSuggestionNumbers
    self.unfinishedSuggestionRun = unfinishedSuggestionRun
    self.lastAppliedSuggestionRunID = lastAppliedSuggestionRunID
    self.suggestionRecoveryOwnerID = suggestionRecoveryOwnerID
    self.speakerCountOverride = speakerCountOverride
    self.speakerDisplayNames = speakerDisplayNames
  }

  enum CodingKeys: String, CodingKey {
    case suggestionStarts, suggestionBatch, issuedSuggestionNumbers, unfinishedSuggestionRun,
      lastAppliedSuggestionRunID, suggestionRecoveryOwnerID
    case slices, timelineRemovals, cutSuggestions, speakerCountOverride, speakerDisplayNames
  }

  /// Lenient decode: a project persisted before cut suggestions / speaker overrides
  /// joined the document is missing those keys — default them rather than failing the
  /// whole decode (mirrors `ProjectState`'s lenient decoder).
  init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.init(
      slices: try container.decode(IdentifiedArrayOf<Slice>.self, forKey: .slices),
      timelineRemovals: try container.decode(
        IdentifiedArrayOf<TimelineRemoval>.self, forKey: .timelineRemovals),
      cutSuggestions: try container.decodeIfPresent(
        IdentifiedArrayOf<CutSuggestion>.self, forKey: .cutSuggestions) ?? [],
      suggestionStarts: try container.decodeIfPresent(
        SuggestionStarts.self, forKey: .suggestionStarts) ?? SuggestionStarts(),
      suggestionBatch: try container.decodeIfPresent(
        SuggestionBatch.self, forKey: .suggestionBatch),
      issuedSuggestionNumbers: try container.decodeIfPresent(
        [SequenceReservation].self, forKey: .issuedSuggestionNumbers) ?? [],
      unfinishedSuggestionRun: try container.decodeIfPresent(
        SuggestionRunCheckpoint.self, forKey: .unfinishedSuggestionRun),
      lastAppliedSuggestionRunID: try container.decodeIfPresent(
        UUID.self, forKey: .lastAppliedSuggestionRunID),
      suggestionRecoveryOwnerID: try container.decodeIfPresent(
        UUID.self, forKey: .suggestionRecoveryOwnerID),
      speakerCountOverride: try container.decodeIfPresent(
        Int.self, forKey: .speakerCountOverride),
      speakerDisplayNames: try container.decodeIfPresent(
        [String: String].self, forKey: .speakerDisplayNames) ?? [:]
    )
    for candidate in cutSuggestions where candidate.status == .accepted && candidate.naming == nil {
      guard slices[id: candidate.id]?.suggestionTypeID == nil,
        slices[id: candidate.id]?.suggestionNaming == nil,
        SuggestionDefaults.types.contains(where: { $0.id == candidate.productType.rawValue })
      else { continue }
      slices[id: candidate.id]?.suggestionTypeID = candidate.productType.rawValue
    }
  }
}

extension EditorDocumentState {
  /// The document re-keyed to a replacement plan (a force-fresh re-transcribe of the same
  /// source). Word IDs are indices into a plan, so nothing word-keyed survives a plan change
  /// unchanged: slices keep their sample ranges and re-derive membership and snippet by the
  /// editor's overlap rule; cut suggestions describe the old transcript and are dropped, to be
  /// regenerated by auto-suggest. Sample-based removals and speaker overrides carry over.
  func rekeyed(to plan: EditPlan) -> EditorDocumentState {
    var rekeyed = self
    rekeyed.slices = IdentifiedArray(
      uniqueElements: slices.map { slice in
        var updated = slice
        updated.wordIDs = wordIDs(
          anyOverlap: slice.startSample..<slice.endSample, words: plan.words)
        updated.snippet = displaySliceSnippet(sliceSnippet(for: updated.wordIDs, words: plan.words))
        return updated
      })
    rekeyed.cutSuggestions = []
    rekeyed.suggestionBatch = nil
    rekeyed.unfinishedSuggestionRun = nil
    return rekeyed
  }
}
